#define RESOURCE_EXE_ICON 0x100
#define RESOURCE_MAINMENU 0x101

#define MENUITEM_FILE 0x1000
#define MENUITEM_FILE_OPEN (MENUITEM_FILE + 0)

#define MENUITEM_CONFIG 0x1020
#define MENUITEM_CONFIG_VIDEO (MENUITEM_CONFIG + 0)
#define MENUITEM_CONFIG_AUDIO (MENUITEM_CONFIG + 1)
#define MENUITEM_CONFIG_INPUT (MENUITEM_CONFIG + 2)

#define MENUITEM_MISC 0x1040
#define MENUITEM_MISC_ABOUT (MENUITEM_MISC + 0)
