#if 0
// 1980 DOS shit
#define RESOURCE_UNIQUE_ID __COUNTER__
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#define MAINMENU_FILE_OPEN RESOURCE_UNIQUE_ID
#undef RESOURCE_UNIQUE_ID

static WCHAR RESOURCE_MAINMENU[] = L"MAIN_MENU";
static WCHAR RESOURCE_ICON_LOGO[] = L"ICON_LOGO";
static WCHAR RESOURCE_DIALOG_ABOUT[] = L"DIALOG_ABOUT";
static WCHAR RESOURCE_DIALOG_CONFIG[] = L"DIALOG_CONFIG";
#endif
